src/webapp/Pages/Error.cshtml.cs
using System.Diagnostics;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

src/webapp/Pages/ImageAnalysis.cshtml.cs
using Azure;
using Azure.AI.Vision.Common;
using Azure.AI.Vision.ImageAnalysis;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class ImageAnalysisModel : PageModel
    {
        [BindProperty]
        public string ImageUrl { get; set; }

        public ImageAnalysisResult? AnalysisResult = null;

        private readonly string aiServicesKey;
        private readonly string aiServicesRegion;

        public ImageAnalysisModel(IConfiguration configuration)
        {
            aiServicesKey = configuration["AzureAiServices:Key"] ?? throw new ArgumentNullException("AzureAiServices:Key");
            aiServicesRegion = configuration["AzureAiServices:Region"] ?? throw new ArgumentNullException("AzureAiServices:Region");
        }

        public void OnGet()
        {
        }

        public async Task OnPost()
        {
            AzureKeyCredential credential = new(aiServicesKey);
            var serviceOptions = new VisionServiceOptions(new Uri($"https://{aiServicesRegion}.api.cognitive.microsoft.com/"), credential);

            using var imageSource = VisionSource.FromUrl(new Uri(ImageUrl));

            var analysisOptions = new ImageAnalysisOptions()
            {
                Features =
                      ImageAnalysisFeature.CropSuggestions
                    //| ImageAnalysisFeature.Caption
                    //| ImageAnalysisFeature.DenseCaptions
                    | ImageAnalysisFeature.Objects
                    | ImageAnalysisFeature.People
                    | ImageAnalysisFeature.Text
                    | ImageAnalysisFeature.Tags,
            };

            using var analyzer = new ImageAnalyzer(serviceOptions, imageSource, analysisOptions);

            AnalysisResult = await analyzer.AnalyzeAsync();
        }
    }
}

src/webapp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

src/webapp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace webapp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

src/webapp/Pages/ProductSearch.cshtml.cs
using Azure.Identity;
using Azure.Search.Documents;
using Azure.Search.Documents.Indexes;
using Azure.Search.Documents.Indexes.Models;
using Azure.Search.Documents.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class ProductSearchModel : PageModel
    {
        [BindProperty]
        public string SearchKeywords { get; set; } = string.Empty;

        public SearchResults<Product>? SearchResults { get; set; }

        private readonly SearchIndexClient? indexClient;
        private readonly SearchClient? searchClient;

        public string IndexName { get; set; }
        public long DocumentCount { get; set; }

        public ProductSearchModel()
        {
            Uri endpoint = new Uri("https://search-aais-scratch-uksouth-3ad9c956.search.windows.net");

            // Create a client for manipulating search indexes
            indexClient = new SearchIndexClient(endpoint, new DefaultAzureCredential());

            if (indexClient.GetIndexes().All(a => a.Name != "products"))
            {
                // Create a new index
                indexClient.CreateIndex(new SearchIndex("products")
                {
                    Fields = new FieldBuilder().Build(typeof(Product))
                });
            }

            var searchIndex = indexClient.GetIndex("products");
            searchClient = indexClient.GetSearchClient("products");

            IndexName = "products";
            DocumentCount = searchClient.GetDocumentCount();
        }

        public void OnGet()
        {

        }

        public async Task OnPostGenerateCatalog()
        {
            await using SearchIndexingBufferedSender<Product> indexer =
                new SearchIndexingBufferedSender<Product>(searchClient);
            await indexer.UploadDocumentsAsync(GenerateCatalog(count: 2000));
        }

        public void OnPostSearch()
        {
            // Perform the search query
            SearchResults<Product> results = searchClient.Search<Product>(SearchKeywords, new SearchOptions
            {
                IncludeTotalCount = true,
                OrderBy = { "Price desc" },
                Skip = 0,
                Size = 10
            });

            // Store the search results
            SearchResults = results;
        }

        public void OnPostDeleteCatalog()
        {
            indexClient.DeleteIndex("products");

            indexClient.CreateIndex(new SearchIndex("products")
            {
                Fields = new FieldBuilder().Build(typeof(Product))
            });
        }

        public IEnumerable<Product> GenerateCatalog(int count = 1000)
        {
            // Adapted from https://weblogs.asp.net/dfindley/Microsoft-Product-Name-Generator
            var prefixes = new[] { null, "Visual", "Compact", "Embedded", "Expression" };
            var products = new[] { null, "Windows", "Office", "SQL", "FoxPro", "BizTalk" };
            var terms = new[] { "Web", "Robotics", "Network", "Testing", "Project", "Small Business", "Team", "Management", "Graphic", "Presentation", "Communication", "Workflow", "Ajax", "XML", "Content", "Source Control" };
            var type = new[] { null, "Client", "Workstation", "Server", "System", "Console", "Shell", "Designer" };
            var suffix = new[] { null, "Express", "Standard", "Professional", "Enterprise", "Ultimate", "Foundation", ".NET", "Framework" };
            var components = new[] { prefixes, products, terms, type, suffix };

            var random = new Random();
            string RandomElement(string[] values) => values[(int)(random.NextDouble() * values.Length)];
            double RandomPrice() => (random.Next(2, 20) * 100.0) / 2.0 - .01;

            for (int i = 1; i <= count; i++)
            {
                yield return new Product
                {
                    Id = i.ToString(),
                    Name = string.Join(" ", components.Select(RandomElement).Where(n => n != null)),
                    Price = RandomPrice()
                };
            }
        }
    }

    public class Product
    {
        [SimpleField(IsKey = true)]
        public string Id { get; set; }

        [SearchableField(IsFilterable = true)]
        public string Name { get; set; }

        [SimpleField(IsSortable = true)]
        public double Price { get; set; }

        public override string ToString() =>
            $"{Id}: {Name} for {Price:C}";
    }
}

src/webapp/Pages/SentimentAnalysis.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Azure;
using Azure.AI.TextAnalytics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class SentimentAnalysisModel : PageModel
    {

        [BindProperty]
        [Required(ErrorMessage = "Please enter some text to analyse.")]
        [MinLength(1, ErrorMessage = "Please enter some text to analyse.")]
        public string TextToAnalyse { get; set; } = "Analyse this text for me please.";

        public DocumentSentiment? DocumentSentiment = null;

        private readonly string aiServicesKey;
        private readonly string aiServicesRegion;

        public SentimentAnalysisModel(IConfiguration configuration)
        {
            aiServicesKey = configuration["AzureAiServices:Key"] ?? throw new ArgumentNullException("AzureAiServices:Key");
            aiServicesRegion = configuration["AzureAiServices:Region"] ?? throw new ArgumentNullException("AzureAiServices:Region");
        }

        public async Task OnGet()
        {
            await ProcessAnalysis();
        }

        public async Task OnPost()
        {
            await ProcessAnalysis();
        }

        public async Task ProcessAnalysis()
        {
            AzureKeyCredential credential = new(aiServicesKey);
            TextAnalyticsClient client = new(new Uri($"https://{aiServicesRegion}.api.cognitive.microsoft.com/"), credential);

            var response = await client.AnalyzeSentimentAsync(TextToAnalyse);
            DocumentSentiment = response.Value;
        }
    }
}

src/webapp/Pages/TextTranslate.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Azure;
using Azure.AI.Translation.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Caching.Memory;

namespace MyApp.Namespace
{
    public class TextTranslateModel : PageModel
    {
        private readonly IMemoryCache memoryCache;

        [BindProperty]
        [Required(ErrorMessage = "Please enter some text to translate.")]
        [MinLength(1, ErrorMessage = "Please enter some text to translate.")]
        public string TextToTranslate { get; set; } = "Translate this text for me please.";

        [BindProperty]
        public string TargetLanguage { get; set; } = "fr";

        public List<string> TargetLanguageOptions { get; set; } = new List<string>();

        public TranslatedTextItem? TranslatedText = null;

        private readonly string aiServicesKey;
        private readonly string aiServicesRegion;

        public TextTranslateModel(IConfiguration configuration, IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache;
            aiServicesKey = configuration["AzureAiServices:Key"] ?? throw new ArgumentNullException("AzureAiServices:Key");
            aiServicesRegion = configuration["AzureAiServices:Region"] ?? throw new ArgumentNullException("AzureAiServices:Region");
        }

        public async Task OnGet()
        {
            await PopulateLanguages();
            await ProcessTranslation();
        }

        public async Task OnPost()
        {
            await PopulateLanguages();
            await ProcessTranslation();
        }

        public async Task ProcessTranslation()
        {
            AzureKeyCredential credential = new(aiServicesKey);
            TextTranslationClient client = new(credential, aiServicesRegion);

            Response<IReadOnlyList<TranslatedTextItem>> response = await client.TranslateAsync(TargetLanguage, TextToTranslate);
            IReadOnlyList<TranslatedTextItem> translations = response.Value;

            TranslatedText = translations.FirstOrDefault();
        }

        public async Task PopulateLanguages()
        {
            if (memoryCache.TryGetValue("TargetLanguageOptions", out List<string> targetLanguageOptions))
            {
                TargetLanguageOptions = targetLanguageOptions;
            }
            else
            {
                await CacheLanguages();
            }
        }

        public async Task CacheLanguages()
        {
            AzureKeyCredential credential = new(aiServicesKey);
            TextTranslationClient client = new(credential, aiServicesRegion);

            var languages = await client.GetLanguagesAsync();
            var languagesToCache = languages.Value.Translation.Select(x => x.Key).ToList();

            memoryCache.Set("TargetLanguageOptions", languagesToCache);

            TargetLanguageOptions = languagesToCache;
        }
    }
}

src/webapp/Pages/UploadImage.cshtml.cs
using Azure.Identity;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class UploadImageModel : PageModel
    {
        [BindProperty]
        public IFormFile? ImageFile { get; set; }

        private readonly string storageAccountName;

        public UploadImageModel(IConfiguration configuration)
        {
            storageAccountName = configuration["AppData:StorageAccountName"] ?? throw new ArgumentNullException("AppData:StorageAccountName");
        }

        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var blobContainer = GetBlobContainer();
            var blobName = Guid.NewGuid().ToString() + Path.GetExtension(ImageFile.FileName);
            var blobClient = blobContainer.GetBlobClient(blobName);

            using (var stream = ImageFile.OpenReadStream())
            {
                await blobClient.UploadAsync(stream);
            }

            return RedirectToPage();
        }

        private BlobContainerClient GetBlobContainer()
        {
            var credential = new DefaultAzureCredential();
            var blobServiceClient = new BlobServiceClient(new Uri($"https://{storageAccountName}.blob.core.windows.net/"), credential);
            var blobContainerClient = blobServiceClient.GetBlobContainerClient("images");
            return blobContainerClient;
        }
    }
}

src/webapp/Pages/ViewImages.cshtml.cs
using Azure.Identity;
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MyApp.Namespace
{
    public class ViewImagesModel : PageModel
    {
        public IEnumerable<Image> Images { get; set; }

        private readonly string storageAccountName;

        public ViewImagesModel(IConfiguration configuration)
        {
            storageAccountName = configuration["AppData:StorageAccountName"] ?? throw new ArgumentNullException("AppData:StorageAccountName");
        }

        public async Task OnGetAsync()
        {
            var blobContainer = GetBlobContainer();
            var blobs = blobContainer.GetBlobsAsync();
            var images = new List<Image>();

            await foreach (var blob in blobs)
            {
                var blobClient = blobContainer.GetBlobClient(blob.Name);
                var url = blobClient.Uri.ToString();
                images.Add(new Image { Url = url });
            }

            Images = images;
        }

        private BlobContainerClient GetBlobContainer()
        {
            var credential = new DefaultAzureCredential();
            var blobServiceClient = new BlobServiceClient(new Uri($"https://{storageAccountName}.blob.core.windows.net/"), credential);
            var blobContainerClient = blobServiceClient.GetBlobContainerClient("images");
            return blobContainerClient;
        }
    }

    public class Image
    {
        public string Url { get; set; }
    }
}

src/webapp/Pages/ImageAnalysis.cshtml
@page
@using MyApp.Namespace
@model ImageAnalysisModel
@{
    ViewData["Title"] = "Image Analysis";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-4 text-center">Image Analysis</h1>
            <p class="text-center">This example uses the
                <a href="https://learn.microsoft.com/en-gb/azure/ai-services/computer-vision/overview-image-analysis?tabs=4-0"
                    target="_blank"> computer vision services</a> which is part of Azure AI Services.
            </p>

            <form method="post">
                <div class="form-group">
                    <label for="ImageUrl">Image URL</label>
                    <input asp-for="ImageUrl" type="text" class="form-control" />
                </div>
                <button type="submit" class="btn btn-primary mt-3">Analyze</button>
            </form>


            @if (Model.AnalysisResult == null)
            {

            }
            else if (Model.AnalysisResult.Reason == Azure.AI.Vision.ImageAnalysis.ImageAnalysisResultReason.Error)
            {
                var errorDetails = Azure.AI.Vision.ImageAnalysis.ImageAnalysisErrorDetails.FromResult(Model.AnalysisResult);

                <div class="alert alert-danger" role="alert">
                    <h4 class="alert-heading">Error</h4>
                    <p>Reason: @errorDetails.Reason</p>
                    <p>Error Code: @errorDetails.ErrorCode</p>
                    <p>Message: @errorDetails.Message</p>
                </div>
            }
            else if (Model.AnalysisResult != null && !string.IsNullOrEmpty(Model.ImageUrl))
            {
                <div class="mt-4">
                    <img src="@Model.ImageUrl" class="img-fluid" alt="Image">

                    @if (Model.AnalysisResult.Caption != null)
                    {
                        <div class="card mt-3">
                            <div class="card-header">
                                <h2>Caption</h2>
                            </div>
                            <div class="card-body">
                                <p class="card-text">
                                    @Model.AnalysisResult.Caption.Content, Confidence @Model.AnalysisResult.Caption.Confidence
                                </p>
                            </div>
                        </div>
                    }

                    @if (Model.AnalysisResult.Objects != null)
                    {
                        <div class="card mt-3">
                            <div class="card-header">
                                <h2>Objects</h2>
                            </div>
                            <div class="card-body">
                                @foreach (var detectedObject in Model.AnalysisResult.Objects)
                                {
                                    <p class="card-text">
                                        @detectedObject.Name, Bounding box @detectedObject.BoundingBox, Confidence
                                        @detectedObject.Confidence
                                    </p>
                                }
                            </div>
                        </div>
                    }

                    @if (Model.AnalysisResult.Tags != null)
                    {
                        <div class="card mt-3">
                            <div class="card-header">
                                <h2>Tags</h2>
                            </div>
                            <div class="card-body">
                                @foreach (var tag in Model.AnalysisResult.Tags)
                                {
                                    <p class="card-text">
                                        @tag.Name, Confidence @tag.Confidence
                                    </p>
                                }
                            </div>
                        </div>
                    }

                    @if (Model.AnalysisResult.People != null)
                    {
                        <div class="card mt-3">
                            <div class="card-header">
                                <h2>People</h2>
                            </div>
                            <div class="card-body">
                                @foreach (var person in Model.AnalysisResult.People)
                                {
                                    <p class="card-text">
                                        Bounding box @person.BoundingBox, Confidence @person.Confidence
                                    </p>
                                }
                            </div>
                        </div>
                    }

                    @if (Model.AnalysisResult.CropSuggestions != null)
                    {
                        <div class="card mt-3">
                            <div class="card-header">
                                <h2>Crop Suggestions</h2>
                            </div>
                            <div class="card-body">
                                @foreach (var cropSuggestion in Model.AnalysisResult.CropSuggestions)
                                {
                                    <p class="card-text">
                                        Aspect ratio @cropSuggestion.AspectRatio:, Crop suggestion @cropSuggestion.BoundingBox
                                    </p>
                                }
                            </div>
                        </div>
                    }

                    @if (Model.AnalysisResult.Text != null)
                    {
                        <div class="card mt-3">
                            <div class="card-header">
                                <h2>Text</h2>
                            </div>
                            <div class="card-body">
                                @foreach (var line in Model.AnalysisResult.Text.Lines)
                                {
                                    string pointsToString = "{" + string.Join(',', line.BoundingPolygon.Select(pointsToString =>
                                    pointsToString.ToString())) + "}";

                                    <p class="card-text">Line: '@line.Content', Bounding polygon @pointsToString</p>

                                    foreach (var word in line.Words)
                                    {
                                        pointsToString = "{" + string.Join(',', word.BoundingPolygon.Select(pointsToString =>
                                        pointsToString.ToString())) + "}";

                                        <p class="card-text">Word: '@word.Content', Bounding polygon @pointsToString, Confidence
                                            @word.Confidence</p>
                                    }
                                }
                            </div>
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>

src/webapp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

src/webapp/Pages/ProductSearch.cshtml
@page
@using MyApp.Namespace
@model ProductSearchModel
@{
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-4 text-center">Product Search</h1>
            <p class="text-center">This example uses the
                <a href="https://learn.microsoft.com/en-us/azure/search/" target=" _blank"> Azure AI Search Service</a>
                which is part of Azure AI Services.
            </p>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="mt-4">
            <div class="card mt-3">
                <div class="card-header">
                    <h2>Index Details</h2>
                </div>
                <div class="card-body">
                    <p class="text-center">Search Index: @Model.IndexName</p>
                    <p class="text-center">Document Count: @Model.DocumentCount</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="mt-4">
            <div class="card mt-3">
                <div class="card-header">
                    <h2>Generate Catalog</h2>
                </div>
                <div class="card-body">
                    <form method="post" asp-page-handler="GenerateCatalog">
                        <input type="submit" value="Generate Catalog" class="btn btn-primary" />
                    </form>
                    <form method="post" asp-page-handler="DeleteCatalog">
                        <input type="submit" value="Delete Catalog" class="btn btn-danger mt-2" />
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="mt-4">
            <div class="card mt-3">
                <div class="card-header">
                    <h2>Product Search</h2>
                </div>
                <div class="card-body">
                    <form method="post" asp-page-handler="Search">
                        <input type="text" name="SearchKeywords" placeholder="Enter search keywords" />
                        <input type="submit" value="Search" class="btn btn-primary" />
                    </form>
                </div>
            </div>
        </div>

        @if (Model.SearchResults != null)
        {
            <div class="row justify-content-center">
                <div class="mt-4">
                    <div class="card mt-3">
                        <div class="card-header">
                            <h2>Search Results</h2>
                        </div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var result in Model.SearchResults.GetResults())
                                    {
                                        <tr>
                                            <td>@result.Document.Name</td>
                                            <td>@result.Document.Price</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

src/webapp/Pages/SentimentAnalysis.cshtml
@page
@using MyApp.Namespace
@model SentimentAnalysisModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-4 text-center">Sentiment Analysis</h1>
            <p class="text-center">This example uses the
                <a href="https://learn.microsoft.com/en-us/azure/ai-services/language-service/overview
                    target=" _blank"> Azure AI Language service</a> which is part of Azure AI Services.
            </p>

            <form method="post">
                <div class="form-group">
                    <label for="TextToAnalyse">Text to Analyse</label>
                    <textarea asp-for="TextToAnalyse" class="form-control" rows="4"></textarea>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Analyse</button>
            </form>

            <hr />

            <div class="mt-4">
                <h1 class="display-4 text-center">Analysis Results</h1>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Sentiment</th>
                            <th scope="col">Positive Score</th>
                            <th scope="col">Neutral Score</th>
                            <th scope="col">Negative Score</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.DocumentSentiment?.Sentiment</td>
                            <td>@Model.DocumentSentiment?.ConfidenceScores.Positive</td>
                            <td>@Model.DocumentSentiment?.ConfidenceScores.Neutral</td>
                            <td>@Model.DocumentSentiment?.ConfidenceScores.Negative</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

src/webapp/Pages/TextTranslate.cshtml
@page
@using MyApp.Namespace
@model TextTranslateModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-4 text-center">Text Translator</h1>
            <p class="text-center">This example uses the
                <a href="https://learn.microsoft.com/en-gb/azure/ai-services/translator/text-translation-overview"
                    target="_blank"> text translation services</a> which is part of Azure AI Services.
            </p>

            <form method="post">
                <div class="form-group">
                    <label for="TextToTranslate">Text to Translate</label>
                    <textarea asp-for="TextToTranslate" class="form-control" rows="4"></textarea>
                </div>
                <div class="form-group">
                    <label for="TargetLanguage">Target Language</label>
                    <select asp-for="TargetLanguage" asp-items="@(new SelectList(Model.TargetLanguageOptions))"
                        class="form-control"></select>
                </div>
                <button type="submit" class="btn btn-primary mt-3">Translate</button>
            </form>

            <hr />

            <div class="mt-4">
                <h1 class="display-4 text-center">Translated Text</h1>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th scope="col">Detected Language</th>
                            <th scope="col">Score</th>
                            <th scope="col">Translated To</th>
                            <th scope="col">Translated Text</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>@Model.TranslatedText?.DetectedLanguage?.Language</td>
                            <td>@Model.TranslatedText?.DetectedLanguage?.Score</td>
                            <td>@Model.TranslatedText?.Translations?.FirstOrDefault().To</td>
                            <td>@Model.TranslatedText?.Translations?.FirstOrDefault()?.Text</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

src/webapp/Pages/UploadImage.cshtml
@page
@using MyApp.Namespace
@model UploadImageModel
@{
    ViewData["Title"] = "Upload Image";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="display-4 text-center">Upload Image</h1>

            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="ImageFile">Image File</label>
                    <input asp-for="ImageFile" type="file" class="form-control-file" />
                </div>
                <button type="submit" class="btn btn-primary mt-3">Upload</button>
            </form>
        </div>
    </div>
</div>